kind: pipeline
type: docker
name: integration

steps:
  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    environment:
      SONARSECRET:
        from_secret: sonar_token
    commands:
      - dotnet-sonarscanner begin 
        /k:"easv-devops_BMICalculator_AY_FwQjHEVvRW2O60GSZ" 
        /d:sonar.host.url="http://sonar.setgo.dk:9000" 
        /d:sonar.token="$SONARSECRET" 
        /d:sonar.qualitygate.wait=true
      - dotnet build --no-incremental
      - dotnet-sonarscanner end /d:sonar.token="$SONARSECRET"

---

kind: pipeline
type: docker
name: deliver
depends_on:
  - integration

steps:
  - name: publish-frontend
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      context: bmi-calculator-frontend
      dockerfile: bmi-calculator-frontend/Dockerfile
      repo: hazemalkhani/bmicalculator-frontend
      tags:
        - staging

  - name: publish-backend
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      context: BMICalculatorApi
      dockerfile: BMICalculatorApi/Dockerfile
      repo: hazemalkhani/bmicalculator-backend
      tags:
        - staging

  - name: trigger-update-test
    image: curlimages/curl
    commands:
      - "curl --fail -X GET 'http://62.169.21.165:8080/v1/update' -H 'Authorization: Bearer mytoken'" # Update with your actual endpoint and token
      - sleep 10
    depends_on:
      - publish-frontend
      - publish-backend

  - name: end-to-end-tests
    image: testcafe/testcafe
    commands:
      - testcafe chromium:headless BMICalculatorApi/tests/load.js --disable-native-automation
    depends_on:
      - trigger-update-test

  - name: performance-tests
    image: grafana/k6
    commands:
      - k6 run BMICalculatorApi/tests/load.js
    depends_on:
      - trigger-update-test

---

kind: pipeline
type: docker
name: deploy
depends_on:
  - deliver

steps:
  - name: release-frontend
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      context: bmi-calculator-frontend
      dockerfile: bmi-calculator-frontend/Dockerfile
      repo: hazemalkhani/bmicalculator-frontend
      tags:
        - prod

  - name: release-backend
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      context: BMICalculatorApi
      dockerfile: BMICalculatorApi/Dockerfile
      repo: hazemalkhani/bmicalculator-backend
      tags:
        - prod

  - name: trigger-update-prod
    image: curlimages/curl
    commands:
      - "curl --fail -X GET 'http://62.169.21.166:8080/v1/update' -H 'Authorization: Bearer mytoken'" # Update with your actual endpoint and token
      - sleep 10
    depends_on:
      - release-frontend
      - release-backend
