kind: pipeline
type: docker
name: default

steps:
  - name: static-code-analysis-backend
    image: mcr.microsoft.com/dotnet/sdk:8.0
    environment:
      SONAR_TOKEN:
        from_secret: sonar_token
    commands:
      - dotnet tool install --global dotnet-sonarscanner
      - export PATH="$PATH:/root/.dotnet/tools"
      - dotnet sonarscanner begin /k:"easv-devops_BMICalculator_AY_FwQjHEVvRW2O60GSZ" /d:sonar.host.url="http://sonar.setgo.dk:9000" /d:sonar.token="${SONAR_TOKEN}" /d:sonar.qualitygate.wait=true
      - dotnet build --no-incremental
      - dotnet sonarscanner end /d:sonar.token="${SONAR_TOKEN}"

  - name: build-and-release-frontend
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: hazemalkhani/bmicalculator-frontend
      tags: latest
      dockerfile: bmi-calculator-frontend/Dockerfile
      context: bmi-calculator-frontend

  - name: build-and-release-backend
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: hazemalkhani/bmicalculator-backend
      tags: latest
      dockerfile: BMICalculatorApi/Dockerfile
      context: BMICalculatorApi

  - name: deploy-to-test
    image: appleboy/drone-ssh
    settings:
      host: 62.169.21.165
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      script:
        - cd ~/bmi_calculator
        - docker-compose --env-file .env.development pull
        - docker-compose --env-file .env.development up -d

  - name: deploy-to-production
    image: appleboy/drone-ssh
    settings:
      host: 62.169.21.166
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      script:
        - cd ~/bmi_calculator
        - docker-compose -f docker-compose.prod.yml pull
        - docker-compose -f docker-compose.prod.yml up -d

trigger:
  branch:
    - master
  event:
    - push
