version: '3.8'

services:
  frontend:
    build: ./bmi-calculator-frontend
    ports:
      - "3000:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  backend:
    build:
      context: .
      dockerfile: BMICalculatorApi/Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - REPO_USER=${DOCKERHUB_USERNAME}
      - REPO_PASS=${DOCKERHUB_PASSWORD}

volumes:
  sqlserver_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
