version: '3.8'

services:
  frontend:
    build: ./bmi-calculator-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.test
    environment:
      - NODE_ENV=test
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://62.169.21.165:8080

  backend:
    build:
      context: .
      dockerfile: BMICalculatorApi/Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env.test
    environment:
      - ASPNETCORE_ENVIRONMENT=Test

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - .env.test
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30

volumes:
  sqlserver_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
