version: '3.8'

services:
  frontend:
    image: hazemalkhani/bmicalculator-frontend:latest
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    image: hazemalkhani/bmicalculator-backend:latest
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=62.169.21.166;Database=bmidb;User Id=sa;Password=700170;TrustServerCertificate=True;

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30  # Checks for updates every 30 seconds
