version: '3.8'

services:
  frontend:
    build:
      context: ./bmi-calculator-frontend
    image: hazemalkhani/bmicalculator_frontend:latest
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=test
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://backend:8080

  backend:
    build:
      context: .
      dockerfile: BMICalculatorApi/Dockerfile
    image: hazemalkhani/bmicalculator_backend:latest
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
      - DB_HOST=db
      - DB_PORT=1433
      - DB_USER=sa
      - REACT_APP_API_URL=http://backend:8080
      - DB_PASSWORD=700170
    depends_on:
      - db
    volumes:
      - ./.env.production:/app/.env.production # Ensure the correct path for the environment file

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=700170
  
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONAR_TOKEN=sqp_3e82c2df837d322f4799bbcfde652f8c87e09777

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
