version: '3.8'

services:
  frontend:
    build: ./bmi-calculator-frontend
    ports:
      - "3000:80"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    networks:
      - bmicalculator_network

  backend:
    build:
      context: .
      dockerfile: BMICalculatorApi/Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env.production
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
    networks:
      - bmicalculator_network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - .env.production
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - bmicalculator_network

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - bmicalculator_network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
    networks:
      - bmicalculator_network

volumes:
  sqlserver_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  bmicalculator_network:
    external: true
